### ISSUE TITLE
Can't see AskYourPDF Extension after install

### ISSUE THREAD

**Issue by Bermyboi** [AskYourPdf/zotero_plugin#1]
Greetings,

I have installed the extension following the instructions in this repository. 
I have Zotero 7, and have signed up to AskYourPDF.

Any suggestions?
Cheers,
Angelo

![AskYourPDF Installed](https://github.com/AskYourPdf/zotero_plugin/assets/159019478/27197968-a03b-45e4-9a09-509c9a23768b)

<img width="329" alt="image" src="https://github.com/AskYourPdf/zotero_plugin/assets/159019478/c1021e88-105a-4a04-b9f3-444c61f4d361">

**Comment by dotcyril** [comment]
+1 on this and still an issue, not yet fixed.

**Comment by Leroy4ux** [comment]
+1 on this and still an issue

**Comment by Bermyboi** [comment]
My workaround has been to have both Zotero 6 & Zotero 7 installed.

Zotero 6 lets me use the AskYourPDF extension.

Zotero 7 is best for allowing me to annotate websites.

**Comment by Gyde04** [comment]
> +1 on this and still an issue, not yet fixed.

Sorry about that, What operating system and version of Zotero 7 are you on? We are trying to deploy a fix as soon as possible

**Comment by Gyde04** [comment]
> +1 on this and still an issue

Sorry about that, What operating system are you using and what version of Zotero 7 are you on?

**Comment by Bermyboi** [comment]
> > +1 on this and still an issue
> 
> Sorry about that, What operating system are you using and what version of Zotero 7 are you on?

Macbook Pro. 
Zotero 7.0.0-beta.79+95d5a5417

**Comment by medianoxlamia** [comment]
Seconding again that this is **still** an issue. I have **Zotero 7.0.2**, using **Sonoma 14.6.1.**

**Comment by drmingler** [comment]
These issues have been resolved in our latest release [here](https://github.com/AskYourPdf/zotero_plugin/releases/tag/1.0.1)
