### ISSUE TITLE
It doesn't work with Zotero 7.0.0-beta.76+91054acfe

### ISSUE THREAD

**Issue by LuckyWuuuuu** [AskYourPdf/zotero_plugin#2]
<img width="403" alt="image" src="https://github.com/AskYourPdf/zotero_plugin/assets/37330735/b1d99ec5-b384-47bf-89b8-66366fe784cf">
I have installed it, and it shows startup finished, but i can't find any button to use askyourpdf
<img width="1386" alt="image" src="https://github.com/AskYourPdf/zotero_plugin/assets/37330735/28d3deb4-6d21-452b-b893-7a2f6c7c2644">
<img width="1386" alt="image" src="https://github.com/AskYourPdf/zotero_plugin/assets/37330735/365dc798-d30f-463b-a2a5-af99d7049e65">

**Comment by victorandraderam** [comment]
I've been presenting the same issue. Zotero version 7.0.0-beta.77+adaa61f2c (64-bit). After the extension is installed, no button is displayed.

**Comment by givemetarte** [comment]
me neither.

**Comment by Veevee923** [comment]
Same here. Any updates to this issue?

**Comment by drmingler** [comment]
These issues have been resolved in our latest release [here](https://github.com/AskYourPdf/zotero_plugin/releases/tag/1.0.1)

**Comment by drmingler** [comment]
These issues have been resolved in our latest release [here](https://github.com/AskYourPdf/zotero_plugin/releases/tag/1.0.1)
